# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/mumumushi/Programs/schedule_face_manager/Smart/gui/res/select_window.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_select_window(object):
    def setupUi(self, select_window):
        select_window.setObjectName("select_window")
        select_window.resize(1280, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(select_window.sizePolicy().hasHeightForWidth())
        select_window.setSizePolicy(sizePolicy)
        select_window.setMinimumSize(QtCore.QSize(1280, 800))
        select_window.setMaximumSize(QtCore.QSize(1280, 800))
        select_window.setAutoFillBackground(True)
        select_window.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.centralwidget = QtWidgets.QWidget(select_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label_background = QtWidgets.QLabel(self.centralwidget)
        self.label_background.setGeometry(QtCore.QRect(0, 0, 1280, 800))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_background.sizePolicy().hasHeightForWidth())
        self.label_background.setSizePolicy(sizePolicy)
        self.label_background.setMinimumSize(QtCore.QSize(1280, 800))
        self.label_background.setMaximumSize(QtCore.QSize(1280, 800))
        self.label_background.setAutoFillBackground(False)
        self.label_background.setText("")
        self.label_background.setPixmap(QtGui.QPixmap(":/background/background.png"))
        self.label_background.setScaledContents(True)
        self.label_background.setAlignment(QtCore.Qt.AlignCenter)
        self.label_background.setObjectName("label_background")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(950, 310, 158, 195))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSpacing(50)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_login = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_login.sizePolicy().hasHeightForWidth())
        self.btn_login.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setBold(True)
        font.setWeight(75)
        self.btn_login.setFont(font)
        self.btn_login.setDefault(False)
        self.btn_login.setFlat(False)
        self.btn_login.setObjectName("btn_login")
        self.verticalLayout.addWidget(self.btn_login)
        self.btn_register = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setBold(True)
        font.setWeight(75)
        self.btn_register.setFont(font)
        self.btn_register.setObjectName("btn_register")
        self.verticalLayout.addWidget(self.btn_register)
        self.btn_exit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setBold(True)
        font.setWeight(75)
        self.btn_exit.setFont(font)
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout.addWidget(self.btn_exit)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 200, 400, 400))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(400, 400))
        self.label.setMaximumSize(QtCore.QSize(400, 400))
        self.label.setAutoFillBackground(False)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/other/pic_people.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        select_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(select_window)
        self.btn_exit.clicked.connect(select_window.close)
        self.btn_login.clicked.connect(self.btn_register.close)
        QtCore.QMetaObject.connectSlotsByName(select_window)

    def retranslateUi(self, select_window):
        _translate = QtCore.QCoreApplication.translate
        select_window.setWindowTitle(_translate("select_window", "select_Window"))
        self.btn_login.setText(_translate("select_window", "登陆"))
        self.btn_register.setText(_translate("select_window", "注册"))
        self.btn_exit.setText(_translate("select_window", "退出"))

import source_rc
