# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'msg_box.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(293, 200)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 30, 251, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.msg_box = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.msg_box.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.msg_box.setContentsMargins(5, 5, 5, 5)
        self.msg_box.setSpacing(5)
        self.msg_box.setObjectName("msg_box")
        self.time = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.time.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time.sizePolicy().hasHeightForWidth())
        self.time.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.time.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        self.time.setFont(font)
        self.time.setAutoFillBackground(False)
        self.time.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.time.setScaledContents(True)
        self.time.setWordWrap(True)
        self.time.setIndent(-1)
        self.time.setObjectName("time")
        self.msg_box.addWidget(self.time)
        self.ask_text = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ask_text.sizePolicy().hasHeightForWidth())
        self.ask_text.setSizePolicy(sizePolicy)
        self.ask_text.setMinimumSize(QtCore.QSize(241, 32))
        self.ask_text.setMaximumSize(QtCore.QSize(300, 60))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.ask_text.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setKerning(True)
        self.ask_text.setFont(font)
        self.ask_text.setAutoFillBackground(False)
        self.ask_text.setIndent(10)
        self.ask_text.setOpenExternalLinks(False)
        self.ask_text.setObjectName("ask_text")
        self.msg_box.addWidget(self.ask_text)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.msg_box.addItem(spacerItem)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(241, 3))
        self.line.setMaximumSize(QtCore.QSize(300, 3))
        self.line.setSizeIncrement(QtCore.QSize(0, 0))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.msg_box.addWidget(self.line)
        self.btn_horizontalLayout = QtWidgets.QHBoxLayout()
        self.btn_horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.btn_horizontalLayout.setContentsMargins(0, 0, -1, -1)
        self.btn_horizontalLayout.setSpacing(0)
        self.btn_horizontalLayout.setObjectName("btn_horizontalLayout")
        self.btn_del = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_del.sizePolicy().hasHeightForWidth())
        self.btn_del.setSizePolicy(sizePolicy)
        self.btn_del.setMinimumSize(QtCore.QSize(28, 24))
        self.btn_del.setMaximumSize(QtCore.QSize(28, 24))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        self.btn_del.setFont(font)
        self.btn_del.setAutoFillBackground(False)
        self.btn_del.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/button/btn_del.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_del.setIcon(icon)
        self.btn_del.setFlat(True)
        self.btn_del.setObjectName("btn_del")
        self.btn_horizontalLayout.addWidget(self.btn_del)
        self.btn_edit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_edit.sizePolicy().hasHeightForWidth())
        self.btn_edit.setSizePolicy(sizePolicy)
        self.btn_edit.setMinimumSize(QtCore.QSize(28, 24))
        self.btn_edit.setMaximumSize(QtCore.QSize(28, 24))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(9)
        self.btn_edit.setFont(font)
        self.btn_edit.setAutoFillBackground(False)
        self.btn_edit.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/button/btn_edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_edit.setIcon(icon1)
        self.btn_edit.setFlat(True)
        self.btn_edit.setObjectName("btn_edit")
        self.btn_horizontalLayout.addWidget(self.btn_edit)
        self.msg_box.addLayout(self.btn_horizontalLayout)
        self.msg_background = QtWidgets.QLabel(Form)
        self.msg_background.setGeometry(QtCore.QRect(0, 0, 300, 200))
        self.msg_background.setMinimumSize(QtCore.QSize(300, 200))
        self.msg_background.setMaximumSize(QtCore.QSize(350, 200))
        self.msg_background.setText("")
        self.msg_background.setPixmap(QtGui.QPixmap(":/background/box_background.png"))
        self.msg_background.setScaledContents(True)
        self.msg_background.setObjectName("msg_background")
        self.msg_background.raise_()
        self.verticalLayoutWidget.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.time.setText(_translate("Form", "8月10 下午19:37"))
        self.ask_text.setText(_translate("Form", "语义请求"))

import source_rc
